#!/bin/zsh
prefix=$HOME/blog/posts/
for file in $HOME/blog/posts/**/*.markdown 
do
  #echo `basename $file .markdown`
  jobname=`basename $file .markdown`
  basedir=$(dirname ${file/$prefix/})
  #echo $basedir
  if [[ ! -d pdf/$basedir ]]; then
    mkdir -p pdf/$basedir
  fi
  sed -e s@{{urls.media}}@$HOME/Dropbox/media@g -e '1,/^}/d' $file \
    | kramdown --template web -o latex | pdflatex -shell-escape -jobname=texput
  mv texput.pdf pdf/$basedir/$jobname.pdf
done
