#!/bin/zsh
TRAPINT() {
  echo "Cleaning up"
  /etc/rc.d/rc.inet1 wwan_down 
  rfkill block wwan
  echo "Cleaning up"
  rfkill unblock wlan
  echo "Cleaning up"
  sleep 1
  #killall congstar
  echo "clean"
  exit 0
}
rfkill block wlan
sleep 1
if rfkill list wwan | grep Hard | grep yes ; then 
  echo "TURN ON WIFI-SWITCH DUMBASS"
  echo "Press any key to continue"
  read
fi
rfkill unblock wwan
sleep 2
/etc/rc.d/rc.inet1 wwan_up
sleep 2

_action() {
  echo "_action_in"
  echo $state
  case "$state" in
    '0')
      echo "0_in"
      echo "AT+CFUN=1\r" > /dev/ttyACM0
      sleep 2
      read -r ans < /dev/cdc-wdm0
      #if [ "$ans" == "ERROR" ] ; then
      #  return 0
      #fi
      echo "$ans"
      echo "AT*ENAP=1,1\r" > /dev/ttyACM0
      sleep 2
      #read -r ans < /dev/cdc-wdm0
      #if [ "$ans" == "ERROR" ] ; then
      #  return 0
      #fi
      state="1"
      ;;
  esac
  echo "_action_out"
}

state="0"
tail -f /var/log/messages | 
while read -r line
do  
  echo "$line"
  case "$line" in 
    (*network connection: connected*)
      echo "connected"
      state="2"
      ;;
    (*leased*)
      echo "leased"
      state="3"
      ;;
    (*network connection: connected*)
      echo "disconnected"
      state="0"
      ;;
  esac
  _action
done


#while true; do
# sleep 1
# echo -n "."
#done
